# Generated by Django 4.2.11 on 2024-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Please enter a valid phone number", max_length=16, null=True
            ),
        ),
    ]
