# Generated by Django 4.2.11 on 2024-03-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientmanager",
            options={
                "verbose_name": "Property Manager",
                "verbose_name_plural": "Property Managers",
            },
        ),
    ]
