# Generated by Django 4.2.3 on 2023-07-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='seamless_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Seamless Status'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='smart_meter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Smart Meter'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='seamless_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Seamless Status'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='smart_meter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Smart Meter'),
        ),
    ]
