# Generated by Django 4.2.3 on 2023-07-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('contracts', '0002_alter_contract_seamless_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_manager_contracts', to='users.clientmanager', verbose_name='Client Manager'),
        ),
    ]
