# Generated by Django 4.2.5 on 2023-10-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_supplier_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='company_reg_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Company Reg Number'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='company_reg_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Company Reg Number'),
        ),
    ]
