# Generated by Django 4.2.6 on 2023-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_company_reg_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('REMOVED', 'Removed'), ('LOCKED', 'Locked'), ('PRICING', 'Pricing'), ('OBJECTION', 'Objection'), ('NEW', 'New')], default='LIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='contract_status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('REMOVED', 'Removed'), ('LOCKED', 'Locked'), ('PRICING', 'Pricing'), ('OBJECTION', 'Objection'), ('NEW', 'New')], default='LIVE', max_length=20),
        ),
    ]
