# Generated by Django 4.2.8 on 2024-01-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_future_standing_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='meter_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DE_ENERGISED', 'De-Energised'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=25, verbose_name='Meter Status'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='meter_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DE_ENERGISED', 'De-Energised'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=25, verbose_name='Meter Status'),
        ),
    ]
