# Generated by Django 4.2.8 on 2024-01-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_meter_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='vat',
            new_name='vat_rate',
        ),
        migrations.RenameField(
            model_name='historicalcontract',
            old_name='vat',
            new_name='vat_rate',
        ),
    ]
