# Generated by Django 4.2.8 on 2024-01-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_rename_vat_contract_vat_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Group'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='client_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Group'),
        ),
    ]
