# Generated by Django 4.2.8 on 2024-01-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_contract_vat_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='vat_declaration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Sent'),
        ),
        migrations.AddField(
            model_name='contract',
            name='vat_declaration_expires',
            field=models.DateField(blank=True, null=True, verbose_name='Vat Declarartion Expiry Date'),
        ),
        migrations.AddField(
            model_name='contract',
            name='vat_declaration_sent',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', verbose_name='Vat Declaration Sent'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='vat_declaration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Sent'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='vat_declaration_expires',
            field=models.DateField(blank=True, null=True, verbose_name='Vat Declarartion Expiry Date'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='vat_declaration_sent',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', verbose_name='Vat Declaration Sent'),
        ),
    ]
