# Generated by Django 4.2.10 on 2024-02-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_alter_contract_future_unit_rate_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('REMOVED', 'Removed'), ('LOCKED', 'Locked'), ('PRICING', 'Pricing'), ('OBJECTION', 'Objection'), ('NEW', 'New'), ('LOST', 'Lost')], default='LIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='contract_status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('REMOVED', 'Removed'), ('LOCKED', 'Locked'), ('PRICING', 'Pricing'), ('OBJECTION', 'Objection'), ('NEW', 'New'), ('LOST', 'Lost')], default='LIVE', max_length=20),
        ),
    ]
