# Generated by Django 4.2.10 on 2024-02-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_alter_contract_contract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='seamless_updated',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', verbose_name='Seamless Contract Updated'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='seamless_updated',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', verbose_name='Seamless Contract Updated'),
        ),
    ]
