# Generated by Django 4.2.10 on 2024-03-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_contract_seamless_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['contract_end_date'], 'permissions': [('can_export_commissions', 'Can export commissions')], 'verbose_name': 'Client Contract', 'verbose_name_plural': 'Client Contracts'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='commission_per_annum',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=10, null=True, verbose_name='Commission Per Annum'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='commission_per_unit',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=10, null=True, verbose_name='Commission Per Unit'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='eac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vat_declaration_expires',
            field=models.DateField(blank=True, null=True, verbose_name='Vat Declaration Expiry Date'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='commission_per_annum',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=10, null=True, verbose_name='Commission Per Annum'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='commission_per_unit',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=10, null=True, verbose_name='Commission Per Unit'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='eac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='vat_declaration_expires',
            field=models.DateField(blank=True, null=True, verbose_name='Vat Declaration Expiry Date'),
        ),
    ]
