# Generated by Django 4.2.10 on 2024-03-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='meter_onboarded',
            field=models.DateField(blank=True, null=True, verbose_name='Meter On Boarded'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='meter_onboarded',
            field=models.DateField(blank=True, null=True, verbose_name='Meter On Boarded'),
        ),
    ]
