# Generated by Django 4.2.11 on 2024-03-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_alter_contract_contract_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='reference_4',
            new_name='supplier_coding',
        ),
        migrations.RenameField(
            model_name='historicalcontract',
            old_name='reference_4',
            new_name='supplier_coding',
        ),
    ]
