# Generated by Django 4.2.11 on 2024-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_rename_reference_4_contract_supplier_coding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='lock_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lock In Date'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='lock_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lock In Date'),
        ),
    ]
