# Generated by Django 4.2.11 on 2024-03-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_contract_lock_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='bid_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='dwellent_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='portal_status',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='bid_id',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='dwellent_id',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='portal_status',
        ),
    ]
