# Generated by Django 4.2.11 on 2024-03-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_remove_contract_bid_id_remove_contract_dwellent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('REMOVED', 'Removed'), ('LOCKED', 'Locked'), ('PRICING', 'Pricing'), ('OBJECTION', 'Objection'), ('NEW', 'New'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('FUTURE', 'Future'), ('CONTRACT_REQUESTED', 'Contract Requested'), ('AWAITING_DA', 'Awaiting DA')], default='LIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='contract_status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('REMOVED', 'Removed'), ('LOCKED', 'Locked'), ('PRICING', 'Pricing'), ('OBJECTION', 'Objection'), ('NEW', 'New'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('FUTURE', 'Future'), ('CONTRACT_REQUESTED', 'Contract Requested'), ('AWAITING_DA', 'Awaiting DA')], default='LIVE', max_length=20),
        ),
    ]
