# Generated by Django 4.2.11 on 2024-03-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_alter_contract_contract_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='future_contract_end_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='future_contract_start_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='future_standing_charge',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='future_supplier',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='future_unit_rate_1',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='future_unit_rate_2',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='future_unit_rate_3',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='future_contract_end_date',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='future_contract_start_date',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='future_standing_charge',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='future_supplier',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='future_unit_rate_1',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='future_unit_rate_2',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='future_unit_rate_3',
        ),
    ]
