# Generated by Django 4.2.11 on 2024-03-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0025_remove_contract_future_contract_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={
                "ordering": ["contract_end_date"],
                "permissions": [("can_export_commissions", "can_access_bulk_quote_template")],
                "verbose_name": "Client Contract",
                "verbose_name_plural": "Client Contracts",
            },
        ),
    ]
