# Generated by Django 4.2.11 on 2024-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0030_alter_contract_contract_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_term",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="contract_term",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
