# Generated by Django 4.2.11 on 2024-05-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0031_contract_contract_term_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="contract_term",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="contract_term",
        ),
    ]
