# Generated by Django 4.2.13 on 2024-06-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_historicalsupplier_meter_email_supplier_meter_email"),
        ("contracts", "0032_remove_contract_contract_term_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="previous_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_contracts",
                to="utilities.supplier",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="previous_supplier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="utilities.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_status",
            field=models.CharField(
                choices=[
                    ("LIVE", "Live"),
                    ("REMOVED", "Removed"),
                    ("LOCKED", "Locked"),
                    ("PRICING", "Pricing"),
                    ("OBJECTION", "Objection"),
                    ("NEW", "New"),
                    ("LOST", "Lost"),
                    ("EXPIRED", "Expired"),
                    ("FUTURE", "Future"),
                    ("CONTRACT_REQUESTED", "Contract Requested"),
                    ("AWAITING_DA", "Awaiting DA"),
                    ("DUPLICATE", "Duplicate"),
                    ("IN_SUPPLIER_BACKLOG", "In Supplier Backlog"),
                    ("DATA_CLEANSE", "Data Cleanse"),
                ],
                default="LIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="contract_status",
            field=models.CharField(
                choices=[
                    ("LIVE", "Live"),
                    ("REMOVED", "Removed"),
                    ("LOCKED", "Locked"),
                    ("PRICING", "Pricing"),
                    ("OBJECTION", "Objection"),
                    ("NEW", "New"),
                    ("LOST", "Lost"),
                    ("EXPIRED", "Expired"),
                    ("FUTURE", "Future"),
                    ("CONTRACT_REQUESTED", "Contract Requested"),
                    ("AWAITING_DA", "Awaiting DA"),
                    ("DUPLICATE", "Duplicate"),
                    ("IN_SUPPLIER_BACKLOG", "In Supplier Backlog"),
                    ("DATA_CLEANSE", "Data Cleanse"),
                ],
                default="LIVE",
                max_length=20,
            ),
        ),
    ]
