# Generated by Django 4.2.13 on 2024-06-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0033_contract_previous_supplier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="previous_supplier",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="previous_supplier",
        ),
    ]
