# Generated by Django 4.2.13 on 2024-06-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_historicalsupplier_meter_email_supplier_meter_email"),
        ("contracts", "0034_remove_contract_previous_supplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="previous_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_contracts",
                to="utilities.supplier",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="supplier_changed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="previous_supplier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="utilities.supplier",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="supplier_changed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
