# Generated by Django 4.2.13 on 2024-06-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0035_contract_previous_supplier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="previous_supplier",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="supplier_changed_date",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="previous_supplier",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="supplier_changed_date",
        ),
    ]
