# Generated by Django 4.2.13 on 2024-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0036_remove_contract_previous_supplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="directors_approval_date",
            field=models.DateField(blank=True, null=True, verbose_name="Directors Approval Date"),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="directors_approval_date",
            field=models.DateField(blank=True, null=True, verbose_name="Directors Approval Date"),
        ),
    ]
