# Generated by Django 4.2.14 on 2024-08-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0037_contract_directors_approval_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="seed_stock",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")], default="NO", verbose_name="Seed Stock"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="seed_stock",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")], default="NO", verbose_name="Seed Stock"
            ),
        ),
    ]
