# Generated by Django 4.2.15 on 2024-08-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_historicalsupplier_meter_email_supplier_meter_email"),
        ("contracts", "0038_contract_seed_stock_historicalcontract_seed_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="bid_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="BID ID"),
        ),
        migrations.AddField(
            model_name="contract",
            name="dwellent_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dwellent ID"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="future_contract_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Future Contract End Date"),
        ),
        migrations.AddField(
            model_name="contract",
            name="future_contract_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Future Contract Start Date"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="future_standing_charge",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="Future Standing Charge",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="future_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="future_suppliers",
                to="utilities.supplier",
                verbose_name="Future Supplier",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="future_unit_rate_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Future Unit Rate 1",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="future_unit_rate_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Future Unit Rate 2",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="future_unit_rate_3",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Future Unit Rate 3",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="portal_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Portal Status"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="bid_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="BID ID"),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="dwellent_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dwellent ID"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="future_contract_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Future Contract End Date"),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="future_contract_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Future Contract Start Date"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="future_standing_charge",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="Future Standing Charge",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="future_supplier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="utilities.supplier",
                verbose_name="Future Supplier",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="future_unit_rate_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Future Unit Rate 1",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="future_unit_rate_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Future Unit Rate 2",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="future_unit_rate_3",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Future Unit Rate 3",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="portal_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Portal Status"
            ),
        ),
    ]
