# Generated by Django 4.2.8 on 2024-01-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='loa',
            field=models.DateField(blank=True, null=True, verbose_name='Letter of Authority'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='loa',
            field=models.DateField(blank=True, null=True, verbose_name='Letter of Authority'),
        ),
    ]
