# Generated by Django 4.2.10 on 2024-02-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_loa_historicalclient_loa'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_lost',
            field=models.BooleanField(default=False, verbose_name='Lost Client'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='is_lost',
            field=models.BooleanField(default=False, verbose_name='Lost Client'),
        ),
    ]
