# Generated by Django 4.2.10 on 2024-03-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_is_lost_historicalclient_is_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_onboarded',
            field=models.DateField(blank=True, null=True, verbose_name='Client Onboarded'),
        ),
        migrations.AddField(
            model_name='client',
            name='originator',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Originator'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='client_onboarded',
            field=models.DateField(blank=True, null=True, verbose_name='Client Onboarded'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='originator',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Originator'),
        ),
    ]
