# Generated by Django 4.2.11 on 2024-04-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_client_onboarded_client_originator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
