# Generated by Django 4.2.11 on 2024-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_client_notes_historicalclient_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_term",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Client Term"
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="client_term",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Client Term"
            ),
        ),
    ]
