# Generated by Django 4.2.11 on 2024-05-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_client_client_term_historicalclient_client_term"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="client_term",
        ),
        migrations.RemoveField(
            model_name="historicalclient",
            name="client_term",
        ),
        migrations.AddField(
            model_name="client",
            name="contract_term",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Contract Term"
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="contract_term",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Contract Term"
            ),
        ),
    ]
