# Generated by Django 4.2.14 on 2024-08-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_client_export_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="export_confirmed",
            field=models.BooleanField(default=False, verbose_name="Confirmation of Export"),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="export_confirmed",
            field=models.BooleanField(default=False, verbose_name="Confirmation of Export"),
        ),
    ]
