# Generated by Django 4.2.3 on 2023-08-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
        ('objections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='new_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_suppliers', to='utilities.supplier', verbose_name='New Supplier'),
        ),
    ]
