# Generated by Django 4.2.3 on 2023-08-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('utilities', '0001_initial'),
        ('objections', '0002_alter_objection_new_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_objections', to='clients.client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='objecting_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objecting_suppliers', to='utilities.supplier', verbose_name='Objecting Supplier'),
        ),
    ]
