# Generated by Django 4.2.6 on 2023-11-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='meter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='meter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
