# Generated by Django 4.2.10 on 2024-03-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_is_lost_historicalclient_is_lost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eac_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eac_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_per_annum', models.DecimalField(decimal_places=3, max_digits=10)),
                ('commission_per_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_commissions', to='clients.client')),
            ],
            options={
                'verbose_name': 'Gas Commission',
                'verbose_name_plural': 'Gas Commissions',
            },
        ),
        migrations.CreateModel(
            name='ElectricityCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eac_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eac_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_per_annum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_per_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_commissions', to='clients.client')),
            ],
            options={
                'verbose_name': 'Electricity Commission',
                'verbose_name_plural': 'Electricity Commissions',
            },
        ),
    ]
